Fix issues with missing 'bignumber.js' module
These are changes to package-lock.json that my local npm installation
made during 'npm install'.

These seem to fix the problem with a missing bignumber.js module,
i.e. with trustlines/netstats-client-next:master27 I get the following
error:

,----
| Status: Downloaded newer image for trustlines/netstats-client-next:master27
| internal/modules/cjs/loader.js:638
|     throw err;
|     ^
|
| Error: Cannot find module 'bignumber.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
|     at Module.require (internal/modules/cjs/loader.js:692:17)
|     at require (internal/modules/cjs/helpers.js:25:18)
|     at Object.<anonymous> (/src/node_modules/web3/lib/utils/utils.js:37:17)
|     at Module._compile (internal/modules/cjs/loader.js:778:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
|     at Module.load (internal/modules/cjs/loader.js:653:32)
|     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
|     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`----